Repository gardener/landscaper-service, pull requests merged in 2022-09, with the labels that each got.

#43 fix schema definition for avs
  .landscaper/blueprint/blueprint.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#44 fix availability configuration settings in laas blueprint
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-execution.yaml
  charts/landscaper-service/templates/_helpers.tpl
  charts/landscaper-service/values.yaml
  integration-test/pkg/tests/test_install_laas.go
Labels: needs/ok-to-test, needs/review, size/s

#45 fix indentation for availabilityMontoring config key
  charts/landscaper-service/templates/_helpers.tpl
Labels: needs/ok-to-test, needs/review, size/xs

#48 prevent buffering of integration test output
  hack/integration-test.sh
  integration-test/docker/Dockerfile
Labels: needs/ok-to-test, needs/review, size/s

#49 make the container names configurable
  .landscaper/blueprint/deploy-execution.yaml
  charts/landscaper-service/templates/_helpers.tpl
  charts/landscaper-service/templates/deployment-controller.yaml
  charts/landscaper-service/templates/deployment-webhooks.yaml
  charts/landscaper-service/values.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/s

#50 More logs for Availability Monitoring
  pkg/controllers/avmonitorregistration/controller.go
  pkg/controllers/avuploader/controller.go
  pkg/controllers/healthwatcher/controllger.go
Labels: needs/ok-to-test, needs/changes, needs/review, size/s

#52 update github.com/emicklei/go-restful to version v2.16.0
  go.mod
  go.sum
  vendor/github.com/emicklei/go-restful/.gitignore
  vendor/github.com/emicklei/go-restful/.travis.yml
  vendor/github.com/emicklei/go-restful/CHANGES.md
  vendor/github.com/emicklei/go-restful/Makefile
  vendor/github.com/emicklei/go-restful/README.md
  vendor/github.com/emicklei/go-restful/container.go
  vendor/github.com/emicklei/go-restful/cors_filter.go
  vendor/github.com/emicklei/go-restful/curly.go
  vendor/github.com/emicklei/go-restful/custom_verb.go
  vendor/github.com/emicklei/go-restful/jsr311.go
  vendor/github.com/emicklei/go-restful/parameter.go
  vendor/github.com/emicklei/go-restful/path_processor.go
  vendor/github.com/emicklei/go-restful/request.go
  vendor/github.com/emicklei/go-restful/response.go
  vendor/github.com/emicklei/go-restful/route.go
  vendor/github.com/emicklei/go-restful/route_builder.go
  vendor/github.com/emicklei/go-restful/route_reader.go
  vendor/github.com/emicklei/go-restful/service_error.go
  vendor/github.com/emicklei/go-restful/web_service.go
  vendor/modules.txt
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#53 Add more logs
  pkg/controllers/avmonitorregistration/controller.go
  pkg/controllers/avuploader/controller.go
  pkg/controllers/healthwatcher/controllger.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#54 Fix AV Monitoring
  pkg/controllers/avmonitorregistration/controller.go
  pkg/controllers/avuploader/controller.go
  pkg/controllers/healthwatcher/controllger.go
Labels: needs/ok-to-test, needs/review, size/xs

#55 update fluentbit to version 1.8.15
  .landscaper/logging-stack/resources.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#56 update landscaper to version v0.36.0
  .landscaper/component-references.yaml
Labels: needs/ok-to-test, needs/review, size/xs
