Repository gardener/landscaper-service, pull requests merged in 2022-01, with the labels that each got.

#7 [Draft] add documentation
  docs/README.md
  docs/gettingstarted/configure-service-targets.md
  docs/gettingstarted/create-landscaper-deployment.md
  docs/usage/Instances.md
  docs/usage/LandscaperDeployments.md
  docs/usage/ServiceTargetConfigs.md
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/l

#8 Some docu changes
  docs/gettingstarted/configure-service-targets.md
  docs/gettingstarted/create-landscaper-deployment.md
  docs/usage/Instances.md
  docs/usage/LandscaperDeployments.md
  docs/usage/ServiceTargetConfigs.md
Labels: needs/ok-to-test, needs/review, size/s

#9 change service target config ordering
  docs/usage/ServiceTargetConfigs.md
  pkg/controllers/landscaperdeployments/reconcile.go
  pkg/controllers/landscaperdeployments/reconcile_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/s
