Repository gardener/landscaper-service, pull requests merged in 2023-04, with the labels that each got.

#130 Default resource settings
  charts/landscaper-service-target-shoot-sidecar-server/values.yaml
  charts/landscaper-service/templates/deployment-webhooks.yaml
  charts/landscaper-service/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs, area/ipcei

#132 No minor shoot version and upgrade to Landscaper v0.54.0
  .landscaper/blueprint/shoot-config.json
  .landscaper/landscaper-instance/blueprint/shoot/deploy-execution.yaml
  .landscaper/landscaper-instance/component-references.yaml
  go.mod
  go.sum
  integration-test/go.mod
  integration-test/go.sum
  integration-test/vendor/modules.txt
  pkg/controllers/instances/controller.go
  vendor/github.com/gardener/landscaper/controller-utils/pkg/webhook/certificates.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/s

#135 restart laas deployment on config change
  charts/landscaper-service/templates/deployment-controller.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs

#137 update landscaper to v0.55.0
  .landscaper/landscaper-instance/component-references.yaml
  go.mod
  go.sum
  integration-test/go.mod
  integration-test/go.sum
  integration-test/vendor/modules.txt
  vendor/modules.txt
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s, status/accepted

#133 shoot high availability
  .landscaper/landscaper-instance/blueprint/shoot/deploy-execution.yaml
  .landscaper/landscaper-instance/definition/shoot-configuration.json
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/type_instance.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/type_landscaperdeployment.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/types_shared.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/v1alpha1/types_instance.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/v1alpha1/types_landscaperdeployment.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/v1alpha1/types_shared.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/v1alpha1/zz_generated.conversion.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/.schemes/core-v1alpha1-Instance.json
  pkg/apis/.schemes/core-v1alpha1-LandscaperDeployment.json
  pkg/apis/config/types_shoot_config.go
  pkg/apis/config/v1alpha1/types_shoot_config.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/apis/core/type_instance.go
  pkg/apis/core/type_landscaperdeployment.go
  pkg/apis/core/types_shared.go
  pkg/apis/core/v1alpha1/types_instance.go
  pkg/apis/core/v1alpha1/types_landscaperdeployment.go
  pkg/apis/core/v1alpha1/types_shared.go
  pkg/apis/core/v1alpha1/zz_generated.conversion.go
  pkg/apis/core/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/core/zz_generated.deepcopy.go
  pkg/apis/openapi/openapi_generated.go
  pkg/apis/validation/instance.go
  pkg/apis/validation/landscaperdeployment.go
  pkg/apis/validation/shared.go
  pkg/controllers/instances/reconcile.go
  pkg/controllers/instances/reconcile_test.go
  pkg/controllers/instances/testdata/reconcile/test2/instance.yaml
  pkg/crdmanager/crdresources/landscaper-service.gardener.cloud_instances.yaml
  pkg/crdmanager/crdresources/landscaper-service.gardener.cloud_landscaperdeployments.yaml
  pkg/webhook/instances_test.go
  pkg/webhook/landscaperdeployment_test.go
  pkg/webhook/webhook.go
  pkg/webhook/webhook_suite_test.go
Labels: kind/api-change, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xl, area/ipcei

#138 upgrade garden linux version
  .landscaper/blueprint/shoot-config.json
Labels: needs/ok-to-test, needs/review, size/xs, area/ipcei

#139 inrease webhook replicas
  pkg/apis/installation/installation.go
Labels: needs/ok-to-test, needs/review, size/xs, area/ipcei

#140 enable automic reconcile for failed landscaper instance installations
  pkg/controllers/instances/reconcile.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs, area/ipcei

#143 set high availability config for instances
  pkg/controllers/landscaperdeployments/reconcile.go
Labels: needs/ok-to-test, needs/review, size/xs, area/ipcei

#144 fix shoot failure tolerance type
  .landscaper/landscaper-instance/definition/shoot-configuration.json
  integration-test/pkg/tests/test_create_deployment.go
  pkg/apis/config/types_shoot_config.go
  pkg/apis/config/v1alpha1/types_shoot_config.go
  pkg/apis/config/v1alpha1/zz_generated.conversion.go
  pkg/apis/config/v1alpha1/zz_generated.deepcopy.go
  pkg/apis/config/zz_generated.deepcopy.go
  pkg/controllers/instances/reconcile.go
  pkg/controllers/instances/reconcile_test.go
Labels: kind/api-change, reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m, area/ipcei

#142 update gardenlinux version default
  .landscaper/landscaper-instance/blueprint/shoot/deploy-execution.yaml
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs, area/ipcei

#145 dont cache the gardener service account client
  pkg/controllers/instances/controller.go
  pkg/controllers/instances/reconcile.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, area/ipcei

#147 Update to golang:1.19.8
  .ci/pipeline_definitions
  Dockerfile
  Makefile
  integration-test/docker/Dockerfile
Labels: needs/ok-to-test, needs/changes, needs/review, size/xs

#148 Upgrade to landscaper v0.47
  go.mod
  go.sum
  integration-test/go.mod
  integration-test/go.sum
  integration-test/vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  integration-test/vendor/modules.txt
  vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/m

#149 update landscaper to version v0.57.0
  .landscaper/landscaper-instance/component-references.yaml
Labels: needs/review, size/xs

#150 dynamic export names
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/installation/installation.go
  pkg/apis/installation/installation.go
  pkg/controllers/instances/reconcile.go
  pkg/controllers/instances/reconcile_test.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/s, area/ipcei
