Repository gardener/landscaper-service, pull requests merged in 2023-07, with the labels that each got.

#178 Increase resource requests
  .landscaper/landscaper-instance/blueprint/landscaper/deploy-execution.yaml
  .landscaper/landscaper-instance/blueprint/ls-service-target-shoot-sidecar-server/deploy-execution.yaml
  charts/landscaper-service-target-shoot-sidecar-server/values.yaml
  charts/landscaper-service/values.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#179 Enable autoscaling of nginx
  .landscaper/ingress-controller/blueprint/deploy-execution.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#180 new manual component descriptor logic
  .ci/component_descriptor
  .ci/component_descriptor_real
  .landscaper/resources.yaml
  hack/create-dummy-cd.py
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#187 HA docu
  docs/architecture/ha-concept.md
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#191 Update to golang1.20
  Dockerfile
  go.mod
  integration-test/go.mod
  integration-test/vendor/modules.txt
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test

#194 update landscaper to v0.72.0
  .landscaper/landscaper-instance/component-references.yaml
  go.mod
  go.sum
  integration-test/go.mod
  integration-test/go.sum
  integration-test/vendor/modules.txt
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/s

#195 disable cache in uncached client
  pkg/utils/uncached_client.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
