Repository gardener/landscaper-service, pull requests merged in 2023-01, with the labels that each got.

#61 add ignore operation annotation
  integration-test/pkg/tests/test_update_deployment.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/apis/core/v1alpha1/constants.go
  integration-test/vendor/github.com/gardener/landscaper-service/pkg/utils/utils.go
  pkg/apis/core/v1alpha1/constants.go
  pkg/controllers/instances/controller.go
  pkg/controllers/instances/reconcile_test.go
  pkg/controllers/instances/testdata/reconcile/test4/instance.yaml
  pkg/controllers/landscaperdeployments/reconcile.go
  pkg/controllers/landscaperdeployments/reconcile_test.go
  pkg/controllers/landscaperdeployments/testdata/reconcile/test6/deployment.yaml
  pkg/controllers/landscaperdeployments/testdata/reconcile/test6/servicetargetconf.yaml
  pkg/utils/utils.go
  pkg/utils/utils_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/l

#64 remove CVE-2022-41720, update to golang:1.18.9
  .ci/pipeline_definitions
  Dockerfile
  integration-test/docker/Dockerfile
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#67 set instance reference first in status before any other operations
  pkg/controllers/landscaperdeployments/reconcile.go
  pkg/controllers/landscaperdeployments/testdata/reconcile/test6/deployment.yaml
  pkg/controllers/landscaperdeployments/testdata/reconcile/test6/servicetargetconf.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#68 Fix AVMonitorRegistration Controller not updating AvailabilityCollection Spec
  pkg/controllers/avmonitorregistration/controller.go
  pkg/controllers/avmonitorregistration/reconcile_test.go
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#70 add ingress-controller component
  .ci/component_descriptor
  .landscaper/component-references.yaml
  .landscaper/ingress-controller/blueprint/blueprint.yaml
  .landscaper/ingress-controller/blueprint/deploy-execution.yaml
  .landscaper/ingress-controller/resources.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, needs/review, size/m

#69 update ServiceTargetConfig documentation
  docs/gettingstarted/configure-service-targets.md
  docs/usage/ServiceTargetConfigs.md
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#71 update landscaper version to v0.44.0
  .landscaper/component-references.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#65 Architecture Documentation
  .gitignore
  docs/architecture/architecture-and-security.md
  docs/architecture/images/architecture-01.png
  docs/architecture/images/core-and-target-cluster.png
  docs/architecture/images/landscaper-instance-creation.png
Labels: needs/ok-to-test, needs/changes, needs/review, size/m

#75 Helm chart to create service account
  .ci/publish-helm-charts
  .landscaper/landscaper-instance/blueprint/installation/blueprint.yaml
  .landscaper/landscaper-instance/blueprint/installation/sidecar-rbac-subinst.yaml
  .landscaper/landscaper-instance/blueprint/installation/sidecar-subinst.yaml
  .landscaper/landscaper-instance/blueprint/sidecar-rbac/blueprint.yaml
  .landscaper/landscaper-instance/blueprint/sidecar-rbac/deploy-execution.yaml
  .landscaper/landscaper-instance/blueprint/sidecar-rbac/export-execution.yaml
  .landscaper/landscaper-instance/resources.yaml
  charts/sidecar-rbac/.helmignore
  charts/sidecar-rbac/Chart.yaml
  charts/sidecar-rbac/templates/_helpers.tpl
  charts/sidecar-rbac/templates/clusterrole-controller.yaml
  charts/sidecar-rbac/templates/clusterrolebinding.yaml
  charts/sidecar-rbac/templates/serviceaccount.yaml
  charts/sidecar-rbac/values.yaml
Labels: reviewed/ok-to-test, needs/ok-to-test, needs/review, size/m
