Repository gardener/landscaper-service, pull requests merged in 2023-08, with the labels that each got.

#199 Upgrade landscaper to version v0.74.0
  .landscaper/landscaper-instance/component-references.yaml
  go.mod
  go.sum
  integration-test/go.mod
  integration-test/go.sum
  integration-test/vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/types_times.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_times.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  integration-test/vendor/modules.txt
  vendor/github.com/gardener/landscaper/apis/core/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/types_times.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_deployitem.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_installation.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_times.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/m

#200 Upgrade landscaper to version v0.75.0
  .landscaper/landscaper-instance/component-references.yaml
  go.mod
  go.sum
  integration-test/go.mod
  integration-test/go.sum
  integration-test/vendor/modules.txt
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/s

#202 wait for landscaper webhook ingress to be ready
  .landscaper/landscaper-instance/blueprint/landscaper/deploy-execution.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#205 update gardenlinux
  .landscaper/blueprint/shoot-config.json
  .landscaper/landscaper-instance/blueprint/shoot/deploy-execution.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#201 Prepare landscaper instance for k8s client settings
  .landscaper/landscaper-instance/blueprint/landscaper/deploy-execution.yaml
  .landscaper/landscaper-instance/definition/landscaper-configuration.json
Labels: reviewed/lgtm, needs/ok-to-test, size/xs

#175 manual deployer installation
  .landscaper/landscaper-instance/blueprint/landscaper/deploy-execution.yaml
  .landscaper/landscaper-instance/blueprint/ls-service-target-shoot-sidecar-server/deploy-execution.yaml
Labels: reviewed/lgtm, needs/ok-to-test, size/m

#198 Dependency update cert-manager:v1.12.3
  .landscaper/logging-stack/resources-cert-manager.yaml
  docs/misc/update-dependencies.md
Labels: reviewed/lgtm, needs/ok-to-test

#210 enforce KeyResource values to be of type string
  pkg/controllers/instances/reconcile_delete.go
  pkg/controllers/landscaperdeployments/reconcile_delete.go
Labels: reviewed/ok-to-test, reviewed/lgtm, needs/ok-to-test, size/xs
