Repository gardener/landscaper-service, pull requests merged in 2024-02, with the labels that each got.

#287 Update landscaper version to v0.95.0
  .landscaper/ocm-settings.yaml
  go.mod
  go.sum
  integration-test/go.mod
  integration-test/go.sum
  integration-test/vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  integration-test/vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  integration-test/vendor/modules.txt
  vendor/github.com/gardener/landscaper/apis/core/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_execution.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/types_shared.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.conversion.go
  vendor/github.com/gardener/landscaper/apis/core/v1alpha1/zz_generated.deepcopy.go
  vendor/github.com/gardener/landscaper/apis/core/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: needs/ok-to-test, needs/review, size/m

#288 fix ingress controller tag
  .landscaper/ingress-controller/blueprint/deploy-execution.yaml
Labels: needs/ok-to-test, needs/review, size/xs

#289 add shoot encryption config
  .landscaper/blueprint/shoot-config.json
  .landscaper/landscaper-instance/blueprint/shoot/deploy-execution.yaml
  .landscaper/landscaper-instance/definition/shoot-configuration.json
  pkg/apis/config/v1alpha1/types_shoot_config.go
Labels: kind/api-change, needs/ok-to-test, needs/review, needs/second-opinion, size/xs

#290 remove deprecated logging-stack
  .landscaper/components.yaml
  .landscaper/logging-stack/blueprint/cert-manager/blueprint.yaml
  .landscaper/logging-stack/blueprint/cert-manager/deploy-execution.yaml
  .landscaper/logging-stack/blueprint/cert-manager/export-execution.yaml
  .landscaper/logging-stack/blueprint/fluentbit/blueprint.yaml
  .landscaper/logging-stack/blueprint/fluentbit/deploy-execution.yaml
  .landscaper/logging-stack/blueprint/installation/blueprint.yaml
  .landscaper/logging-stack/blueprint/installation/cert-manager-subinst.yaml
  .landscaper/logging-stack/blueprint/installation/fluentbit-subinst.yaml
  .landscaper/logging-stack/blueprint/installation/sap-btp-service-operator-subinst.yaml
  .landscaper/logging-stack/blueprint/installation/service-provisioning-subinst.yaml
  .landscaper/logging-stack/blueprint/sap-btp-service-operator/blueprint.yaml
  .landscaper/logging-stack/blueprint/sap-btp-service-operator/deploy-execution.yaml
  .landscaper/logging-stack/blueprint/sap-btp-service-operator/export-execution.yaml
  .landscaper/logging-stack/blueprint/service-provisioning/blueprint.yaml
  .landscaper/logging-stack/blueprint/service-provisioning/deploy-execution.yaml
  .landscaper/logging-stack/blueprint/service-provisioning/export-execution.yaml
  .landscaper/ocm-settings.yaml
Labels: needs/ok-to-test, needs/review, needs/second-opinion, size/xl

#291 disable encryption of landscaper resources
  .landscaper/blueprint/shoot-config.json
Labels: needs/ok-to-test, needs/review, size/xs

#299 add landscaper contexts to encryption config
  .landscaper/blueprint/shoot-config.json
Labels: needs/ok-to-test, needs/review, size/xs
