Repository gardener/landscaper-service, pull requests merged in 2024-08, with the labels that each got.

#416 Kubernetes version 1.28 for shoot clusters
  .landscaper/blueprint/shoot-config.json
Labels: needs/ok-to-test, needs/review, size/xs

#417 add new parameter shootConfigurationUseMergeOverwrite
  .landscaper/blueprint/blueprint.yaml
  .landscaper/blueprint/deploy-execution.yaml
Labels: needs/ok-to-test, size/xs

#420 Fix missing inputs
  .ci/pipeline_definitions
Labels: needs/ok-to-test, needs/review, size/xs

#422 Update landscaper to version v0.113.0
  .landscaper/ocm-settings.yaml
  go.mod
  go.sum
  integration-test/go.mod
  integration-test/go.sum
Labels: needs/ok-to-test, needs/review, size/s

#425 Validate deployers of a LandscaperDeployment
  pkg/apis/validation/landscaperdeployment.go
  pkg/apis/validation/landscaperdeployment_test.go
  pkg/apis/validation/shared.go
  pkg/apis/validation/validation_suite_test.go
Labels: needs/ok-to-test, needs/review, size/m
